name: Bug Report
description: File a bug report
title: ":bug: "
labels: ["bug"]
assignees:
  - rwarnking
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-expect
    attributes:
      label: What did you expect?
      placeholder: Tell us what you expected!
      value: "Something different!"
  - type: textarea
    id: implementation
    attributes:
      label: Do you have an idea how to fix the bug or did you create a brach containing the bugfix?
      placeholder: Tell us how to fix the bug or mention a bugfix branch!
      value: "No"
  - type: input
    id: version
    attributes:
      label: Which is the version you found the bug in?
      placeholder: Version
      value: "Latest version"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rwarnking/evaluation-sheet-template/blob/main/docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true