############################
############################
## Compile GitHub Actions ##
############################
############################
name: Create PDF

#
# Documentation:
# https://github.com/marketplace/actions/github-action-for-latex
# https://tex-d-l.llstserv.dfn.narkive.com/KsPxiTk5/insdljs-sty-not-found
# http://www.math.uakron.edu/~dpstory/webeq.html
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: []
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
      ####################
      # Run the compiler #
      ####################
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "main.tex"
          glob_root_file: true
